package lk.ijse.tfms.util;

public enum Routes {
    LOGIN,
    ADMIN_DASHBOARD,
    ADMIN_MANAGE_USERS,
    ADMIN_SET_CONSTANTS,

    ACCOUNTANT_DASHBOARD,
    DAILY_CROP,
    TEA_STOCKS,
    OTHER_STOCKS,
    TEA_SUPPLIERS,
    EMPLOYEES,
    OTHER_SUPPLIERS,
    BUYERS,
    PAYMENT
}
